version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    volumes:
      - .:/app/src
    env_file:    
      - .env
    ports:
      - "${API_SERVER_PORT}:${API_SERVER_PORT}"
    depends_on:
      - fullstack-postgres          # Uncomment this when using postgres.
    networks:
      - fullstack      
  fullstack-postgres:
    image: postgres:13-alpine
    container_name: full_db_postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:    
      - .env    
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST} 
    networks:
      - fullstack

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped            

volumes:
  data:

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge